### ISSUE TITLE
Cannot load .sounds

### ISSUE THREAD

**Issue by geocine** [cyco/mighty-resource-parser#9]
I can load the other assets except for the Audio . This is what I get
![image](https://user-images.githubusercontent.com/507464/113081863-0b31ad80-920c-11eb-833b-9438e7ca0594.png)
I tried on both Windows 10 and OSX 10.14.6

**Comment by geocine** [comment]
Oh sorry, my audio files were corrupted, everything was 0 bytes, I now found the correct Audio files. The correct way is to extract the data files on a Mac not on Windows. Thank you for this project @cyco . By any chance are you developing a remake for this game?

**Comment by cyco** [comment]
Hey, glad you like the project. I'm using macOS-specific syntax to access the contents of some assets (here https://github.com/cyco/mighty-resource-parser/blob/master/resource-fork.config.js#L12). As far as I know, on Windows the same data would be accessed by prefixing the file name with `._` instead of appending `/../namedfork/rsrc`. I'll try that when I get access to a windows box.

I'm not working on a remake at the moment. In the next weeks I'll be finishing up my reimplementation of _Yoda Stories_ (https://github.com/cyco/webfun) 🤞🥳. Maybe _Power Pete_ is next, but last I checked ppc assembler was not very fun to work with 👎.
